mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: 4.4.6
    pullPolicy: Always
  containerPort: 27017
  service:
    type: ClusterIP
    port: 27017
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  persistence:
    enabled: true
    size: 8Gi
    storageClass: standard
  auth:
    enabled: true
    secretName: mongo-secret
    rootUsernameKey: user
    rootPasswordKey: password
    databaseKey: dbname

redis:
  image:
    repository: bitnami/redis
    tag: 6.2.5
    pullPolicy: Always
  master:
    replicaCount: 1
    containerPort: 6379
    service:
      type: ClusterIP
      port: 6379
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    persistence:
      enabled: true
      existingClaim: redis-master-pvc
      size: 8Gi
      storageClass: standard
      accessModes:
        - ReadWriteOnce
    auth:
      enabled: true
      secretName: redis-secret
      rootPasswordKey: password
  slave:
    replicaCount: 1
    containerPort: 6380
    service:
      type: ClusterIP
      port: 6380
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    persistence:
      enabled: true
      existingClaim: redis-slave-pvc
      size: 8Gi
      storageClass: standard
      accessModes:
        - ReadWriteOnce
    auth:
      enabled: true
      secretName: redis-secret
      rootPasswordKey: password

dbupdater:
  replicaCount: 1
  image:
    repository: docker.io/tacos4brekky/market_analysis-dbupdater
    tag: latest
    pullPolicy: Always
  auth:
    secretName:
      redis: redis-secret
      keys: keys-secret
    hostKey: host
    portKey: port
    passwordKey: password
    rapidapiKey: rapidapi
  containerPort: 5000
  service:
    type: ClusterIP
    port: 5002
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

dbinterface:
  replicaCount: 1
  image:
    repository: docker.io/tacos4brekky/market_analysis-dbinterface
    tag: latest
    pullPolicy: Always
  auth:
    secretName:
      mongo: mongo-secret
      redis: redis-secret
      keys: keys-secret
    usernameKey: user
    passwordKey: password
    hostKey: host
    portKey: port
    databaseKey: dbname
  containerPort: 5000
  service:
    type: ClusterIP
    port: 5003
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi



